services:
  - type: web
    name: my-flask-portfolio
    env: python
    pythonVersion: 3.10.12  # Avoid 3.13
    buildCommand: |
      apt-get update && apt-get install -y build-essential libssl-dev libffi-dev python3-dev
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
